apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: backendapp
spec:
  id: backendapp
  parameters:
    namespace: production
    image: docker.io/vfarcic/backendapp:0.0.0
    host: coe.org
  compositionSelector:
    matchLabels:
      type: backend-db-local
