apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: backendapp
spec:
  connection:
    postgres:
      host:
        value: backendapp-postgresql
      password: 
        valueFrom:
          secretKeyRef:
            name: backendapp-postgresql
