---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: backendapp
spec:
  immediateDeploy: true
  connection:
    postgres:
      uri:
        value: postgres://postgres:Reneeka@23@34.172.19.222:80/backendapp
      # host:
      #   value: 34.172.19.222
      # user:
      #   value: postgres
      # password:
      #   valueFrom:
      #     secretKeyRef:
      #       name: postgresql
      #       key: postgres-password
      # # port:
      # #   value: "80"
      # dbname:
      #   value: backendapp
---
apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: backendapp-videos
spec:
  database: backendapp
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
